defaults: &defaults
  adapter: sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  database: db/my_draft_dev.sqlite3
  <<: *defaults

test: &test
  database: db/my_draft_test.sqlite3
  <<: *defaults

production:
  database: db/my_draft.sqlite3
  <<: *defaults

cucumber:
  <<: *test